name: Deploy Backend

on:
  push:
    branches: ["main"]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:latest

      - name: Create backend.env
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend.env
          echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> backend.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> backend.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend.env
          echo "PORT=5000" >> backend.env
          echo "DB_HOST=db" >> backend.env

      - name: Copy compose & env to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend.env,docker-compose.yml"
          target: ${{ secrets.SERVER_DEPLOY_PATH }}

      - name: Run SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: DOCKER_USERNAME,REPO_NAME,DB_ROOT_PASSWORD,DB_NAME,DB_USER,DB_PASSWORD
          script: |
            cd ${{ secrets.SERVER_DEPLOY_PATH }}
            docker compose down || true
            docker compose pull
            docker compose up -d --build
